version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/var/www
    command: php-fpw
    depemds_on:
      - db
    ports:
      - "9000:9000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secureauth_fb
    ports:
      - "5432:5432"